const catalog = [
  ['Arrays & Hashing', [['Two Sum','Easy'],['Valid Anagram','Easy'],['Group Anagrams','Medium'],['Top K Frequent Elements','Medium'],['Product of Array Except Self','Medium'],['Valid Sudoku','Medium'],['Contains Duplicate','Easy'],['Encode and Decode Strings','Medium'],['Longest Consecutive Sequence','Medium']]],
  ['Two Pointers', [['Valid Palindrome','Easy'],['Two Sum II - Input Array Is Sorted','Medium'],['3Sum','Medium'],['Container With Most Water','Medium'],['Trapping Rain Water','Hard']]],
  ['Sliding Window', [['Best Time to Buy and Sell Stock','Easy'],['Longest Substring Without Repeating Characters','Medium'],['Longest Repeating Character Replacement','Medium'],['Permutation in String','Medium'],['Minimum Window Substring','Hard'],['Sliding Window Maximum','Hard']]],
  ['Stack', [['Valid Parentheses','Easy'],['Min Stack','Medium'],['Evaluate Reverse Polish Notation','Medium'],['Generate Parentheses','Medium'],['Daily Temperatures','Medium'],['Car Fleet','Medium'],['Largest Rectangle in Histogram','Hard']]],
  ['Binary Search', [['Binary Search','Easy'],['Search a 2D Matrix','Medium'],['Koko Eating Bananas','Medium'],['Find Minimum in Rotated Sorted Array','Medium'],['Search in Rotated Sorted Array','Medium'],['Time Based Key-Value Store','Medium'],['Median of Two Sorted Arrays','Hard']]],
  ['Linked List', [['Reverse Linked List','Easy'],['Merge Two Sorted Lists','Easy'],['Reorder List','Medium'],['Remove Nth Node From End of List','Medium'],['Copy List with Random Pointer','Medium'],['Add Two Numbers','Medium'],['Linked List Cycle','Easy'],['Find the Duplicate Number','Medium'],['LRU Cache','Medium'],['Merge k Sorted Lists','Hard'],['Reverse Nodes in k-Group','Hard']]],
  ['Trees', [['Invert Binary Tree','Easy'],['Maximum Depth of Binary Tree','Easy'],['Diameter of Binary Tree','Easy'],['Balanced Binary Tree','Easy'],['Same Tree','Easy'],['Subtree of Another Tree','Easy'],['Lowest Common Ancestor of a Binary Search Tree','Medium'],['Binary Tree Level Order Traversal','Medium'],['Binary Tree Right Side View','Medium'],['Count Good Nodes in Binary Tree','Medium'],['Validate Binary Search Tree','Medium'],['Kth Smallest Element in a BST','Medium'],['Construct Binary Tree from Preorder and Inorder Traversal','Medium'],['Binary Tree Maximum Path Sum','Hard'],['Serialize and Deserialize Binary Tree','Hard']]],
  ['Tries', [['Implement Trie (Prefix Tree)','Medium'],['Design Add and Search Words Data Structure','Medium'],['Word Search II','Hard']]],
  ['Heap / Priority Queue', [['Kth Largest Element in a Stream','Easy'],['Last Stone Weight','Easy'],['K Closest Points to Origin','Medium'],['Kth Largest Element in an Array','Medium'],['Task Scheduler','Medium'],['Design Twitter','Medium'],['Find Median from Data Stream','Hard']]],
  ['Backtracking', [['Subsets','Medium'],['Combination Sum','Medium'],['Permutations','Medium'],['Subsets II','Medium'],['Combination Sum II','Medium'],['Word Search','Medium'],['Palindrome Partitioning','Medium'],['Letter Combinations of a Phone Number','Medium'],['N-Queens','Hard']]],
  ['Graphs', [['Number of Islands','Medium'],['Clone Graph','Medium'],['Max Area of Island','Medium'],['Pacific Atlantic Water Flow','Medium'],['Surrounded Regions','Medium'],['Rotting Oranges','Medium'],['Walls and Gates','Medium'],['Course Schedule','Medium'],['Course Schedule II','Medium'],['Redundant Connection','Medium'],['Number of Connected Components in an Undirected Graph','Medium'],['Graph Valid Tree','Medium'],['Word Ladder','Hard']]],
  ['Advanced Graphs', [['Reconstruct Itinerary','Hard'],['Min Cost to Connect All Points','Medium'],['Network Delay Time','Medium'],['Swim in Rising Water','Hard'],['Alien Dictionary','Hard'],['Cheapest Flights Within K Stops','Medium']]],
  ['1-D Dynamic Programming', [['Climbing Stairs','Easy'],['Min Cost Climbing Stairs','Easy'],['House Robber','Medium'],['House Robber II','Medium'],['Longest Palindromic Substring','Medium'],['Palindromic Substrings','Medium'],['Decode Ways','Medium'],['Coin Change','Medium'],['Maximum Product Subarray','Medium'],['Word Break','Medium'],['Longest Increasing Subsequence','Medium'],['Partition Equal Subset Sum','Medium']]],
  ['2-D Dynamic Programming', [['Unique Paths','Medium'],['Longest Common Subsequence','Medium'],['Best Time to Buy and Sell Stock with Cooldown','Medium'],['Coin Change II','Medium'],['Target Sum','Medium'],['Interleaving String','Medium'],['Longest Increasing Path in a Matrix','Hard'],['Distinct Subsequences','Hard'],['Edit Distance','Hard'],['Burst Balloons','Hard'],['Regular Expression Matching','Hard']]],
  ['Greedy', [['Maximum Subarray','Medium'],['Jump Game','Medium'],['Jump Game II','Medium'],['Gas Station','Medium'],['Hand of Straights','Medium'],['Merge Triplets to Form Target Triplet','Medium'],['Partition Labels','Medium'],['Valid Parenthesis String','Medium']]],
  ['Intervals', [['Insert Interval','Medium'],['Merge Intervals','Medium'],['Non-overlapping Intervals','Medium'],['Meeting Rooms','Easy'],['Meeting Rooms II','Medium'],['Minimum Interval to Include Each Query','Hard']]],
  ['Math & Geometry', [['Rotate Image','Medium'],['Spiral Matrix','Medium'],['Set Matrix Zeroes','Medium'],['Happy Number','Easy'],['Plus One','Easy'],['Pow(x, n)','Medium'],['Multiply Strings','Medium'],['Detect Squares','Medium']]],
  ['Bit Manipulation', [['Single Number','Easy'],['Number of 1 Bits','Easy'],['Counting Bits','Easy'],['Reverse Bits','Easy'],['Missing Number','Easy'],['Sum of Two Integers','Medium'],['Reverse Integer','Medium']]]
]

export const starterProblems = catalog.flatMap(([category, problems]) => problems.map(([title, difficulty]) => ({ title, category, difficulty }))).map((problem, index) => ({ id: index + 1, ...problem, url: '', status: 'new', repetitions: 0, nextReview: null, plannedDate: null, solvedAt: null }))
